version: "3"
services: 
  couchDB:
    image: hyperledger/fabric-couchdb
    container_name: couchdb1
    ports: 
      - "6984:5984"
    environment: 
      -  COUCHDB_USER=
      -  COUCHDB_PASSWORD=
      #네트워크 설정
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
    network_mode: host
  
  Peer1:
    image: hyperledger/fabric-peer
    container_name: peer1.org1.example.com
    ports: 
      - "9051:7051"
      - "9053:7053"
    network_mode: host
    environment: 
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=localhost:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer1.org1.example.com
      - CORE_NEXT=true
      
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=192.168.0.7:7050
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      - CORE_PEER_LOCALMSPID=Org1MSP
      #오버레이 네트워크 설정
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - CORE_PEER_GOSSIP_BOOTSTRAP=192.168.0.7:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_TLS_ENABLED=false
    volumes: 
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: ["peer","node","start"]