version: "3"
services:

  CA:
    image: hyperledger/fabric-ca
    container_name: ca.example.com
    ports:
      - "7054:7054"
    network_mode: host
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.example.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e0cbbf12ccafabd3e572fa52f8111f3ecb170713a0d90a86ff9584c9f0459a75_sk
      #네트워크 설정
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
    volumes:
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    working_dir: /etc/hyperledger/fabric-ca-server
    command: ["fabric-ca-server","start","-b","admin:adminpw","-d"]

  Orderer:
    image: hyperledger/fabric-orderer
    ports:
      - "7050:7050"
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
      #오버레이 네트워크 설정 
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    network_mode: host
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    container_name: orderer.example.com

  couchDB-peer0:
    image: hyperledger/fabric-couchdb
    ports:
      - "5984:5984"
    network_mode: host
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
       #오버레이 네트워크 설정
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
    container_name: couchdb0

  Peer0:
    image: hyperledger/fabric-peer
    network_mode: host
    ports:
      - "8051:7051"
      - "8053:7053"
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=localhost:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_NETWORKID=peer0.org1.example.com
      - CORE_NEXT=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_COMMITTER_LEDGER_ORDERER=localhost:7050
      - CORE_PEER_GOSSIP_IGNORESECURITY=true
      #오버레이 네트워크 설정
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=host
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: ["peer","node","start"]
    container_name: peer0.org1.example.com
    